Repository matheuszpher/FRONT-MYM, pull requests merged in 2023-11, with the labels that each got.

#1 add UI components shadcn/ui
  my-monitor/components.json
  my-monitor/package-lock.json
  my-monitor/package.json
  my-monitor/src/app/globals.css
  my-monitor/src/components/ui/button.tsx
  my-monitor/src/components/ui/input.tsx
  my-monitor/src/components/ui/label.tsx
  my-monitor/src/components/ui/select.tsx
  my-monitor/src/lib/utils.ts
  my-monitor/tailwind.config.js
Labels: good first issue

#2 Adding next auth to the application
  my-monitor/package-lock.json
  my-monitor/package.json
  my-monitor/src/app/(admin-routes)/layout.tsx
  my-monitor/src/app/(admin-routes)/page.tsx
  my-monitor/src/app/(auth-routes)/cadastro/page.tsx
  my-monitor/src/app/(auth-routes)/layout.tsx
  my-monitor/src/app/(auth-routes)/login/page.tsx
  my-monitor/src/app/api/auth/[...nextauth]/route.ts
  my-monitor/src/app/layout.tsx
  my-monitor/src/providers/index.ts
  my-monitor/src/providers/next-auth/sessionProvider.tsx
  my-monitor/src/templates/dashboard/Dashboard.tsx
  my-monitor/src/templates/dashboard/components/index.ts
  my-monitor/src/templates/dashboard/components/logout-button/LogoutButton.tsx
  my-monitor/src/templates/login/Login.tsx
  my-monitor/src/types/index.ts
  my-monitor/src/types/next-auth.d.ts
Labels: enhancement, good first issue

#3 Cadastro validation with Zod and React Hook Form.
  my-monitor/package-lock.json
  my-monitor/package.json
  my-monitor/src/components/ui/radio-group.tsx
  my-monitor/src/hooks/useCadastroUser.ts
  my-monitor/src/schema/schemaFormCadastro.ts
  my-monitor/src/templates/cadastro/Cadastro.tsx
  my-monitor/src/templates/cadastro/components/form-cadastro/FormCadastro.tsx
  my-monitor/src/templates/cadastro/components/index.ts
  my-monitor/src/templates/cadastro/components/radio-group/RadioGroupRegister.tsx
  my-monitor/src/types/index.ts
Labels: enhancement, good first issue

#8 :sparkles: feat : Implementação Tela de Cadastro
  my-monitor/public/images/LogoBranca.png
  my-monitor/public/images/Pessoas-lendo-Cadastro.png
  my-monitor/src/app/(auth-routes)/cadastro/page.tsx
  my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
  my-monitor/src/components/cadastro/radio-group/RadioGroupRegister.tsx
  my-monitor/src/components/homepage/aside/AsideHomePageCadastro.tsx
  my-monitor/src/components/homepage/header/HeaderHomepage.tsx
  my-monitor/src/components/homepage/icons/ConfirmaPasswordGreenIcon.tsx
  my-monitor/src/components/homepage/icons/EmailGreenIcon.tsx
  my-monitor/src/components/homepage/icons/PasswordGreenIcon.tsx
  my-monitor/src/components/homepage/icons/TokenIcon.tsx
  my-monitor/src/components/homepage/icons/UserIcon.tsx
  my-monitor/src/components/homepage/index.tsx
  my-monitor/src/components/ui/radio-group.tsx
  my-monitor/src/schema/schemaFormCadastro.ts
  my-monitor/src/templates/cadastro/Cadastro.tsx
  my-monitor/src/templates/homepagecadastro/HomepageCadastro.tsx
  my-monitor/src/templates/index.ts
  my-monitor/src/types/index.ts
Labels: good first issue

#10 🐛 fix
  my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
  my-monitor/src/components/cadastro/radio-group/RadioGroupRegister.tsx
  my-monitor/src/components/footer/Footer.tsx
  my-monitor/src/components/homepage/icons/TokenIcon.tsx
  my-monitor/src/hooks/useCadastroUser.ts
  my-monitor/src/templates/cadastro/Cadastro.tsx
  my-monitor/src/templates/homepage/Homepage.tsx
  my-monitor/src/templates/homepagecadastro/HomepageCadastro.tsx
Labels: bug
